[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/images/*.jpg"
[headers.values]
  Content-Type = "image/jpeg"

[[headers]]
for = "/images/*.png"
[headers.values]
  Content-Type = "images/png"

[[headers]]
for = "/videos/*.mp4"
[headers.values]
  Content-Type = "video/mp4"

[[headers]]
for = "/*.png"
[headers.values]
Content-Type = "image/png"
